### ISSUE TITLE
repository citation

### ISSUE THREAD

**Issue by BaptisteCecconi** [STBadman/Radio-Public#2]
Hi, 
Your repository is referenced by a paper under review. It would be good to publish the code to Zenodo and get a DOI, so that citation can be fully implemented and tracked.

**Comment by STBadman** [comment]
Thanks for the suggestion! After a bit of cleaning to add an environment file and a readme (348f51e), we made a zenodo link under a v0.1 release available here: https://zenodo.org/account/settings/github/repository/STBadman/Radio-Public
